[build]
# The public URL from which assets are to be served.
public_url = "https://music.mariolopez.org/leptos/"
# Allow disabling sub-resource integrity (SRI)
no_sri = true

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 3000
# Base path to serve from, should match public_url without the domain
path = "/leptos/"
