#!/usr/bin/env sh

# Run husky
. "$(dirname -- "$0")/_/husky.sh"

# Run update and build for front-end projects
npm run update-and-build:frontend

# Add command to stage any changes made by the build process
git add .
